%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Temp\xkleme13\MKS23\cv06-tempsens\ntc.csv
%
% Auto-generated by MATLAB on 02-Nov-2023 14:57:34

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Temp", "Value"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ntc = readtable("C:\Temp\xkleme13\MKS23\cv06-tempsens\ntc.csv", opts);


%% Clear temporary variables
clear opts